
generators:
  circuit:
    type: 'random'
    args:
      num_qubits: 16
      num_gates: 128
      seed: 0
  noise:
    type: 'uniform'
    args:
      mean: 1.0e-2
      std: 3.0e-3
      seed: 0

# Model
hidden_layers: [128, 128]
minibatch_size: 2048
batch_size: 32768
sgd_iters: 15
lr: 5.0e-5

# Resources
num_workers: 18
envs_per_worker: 8
num_gpus: 1
