
generators:
  circuit:
    type: 'random'
    args:
      num_qubits: 5
      num_gates: 64
  noise:
    type: 'uniform'
    args:
      mean: 1.0e-2
      std: 3.0e-3

# Model
hidden_layers: [96, 96, 96]
minibatch_size: 256
batch_size: 8192

# Resources
num_workers: 18
envs_per_worker: 8
num_gpus: 1
