
circuit_generator:
  type: 'dataset'
  args:
    path: 'data/circuits/16q'

routing_methods: ['basic', 'stochastic', 'sabre']
calibration_data: 'data/calibration/guadalupe.json'
use_tqdm: true
seed: 0
