
circuit_generator:
  type: 'random'
  args:
    num_gates: 64

routing_methods: ['basic', 'stochastic', 'sabre']
calibration_data: 'data/calibration/guadalupe.json'
num_circuits: 200
use_tqdm: true
seed: 0
