
circuit_generator:
  type: 'random'
  args:
    num_gates: 64
noise_generator:
  type: 'kde_calibration'
  args:
    path: 'data/calibration/manila.json'

seed: 0

# Model
hidden_layers: [128, 128]
embedding_dim: 3
minibatch_size: 512
batch_size: 8192
sgd_iters: 5
lr_schedule:
    - [0, 3.0e-4]
    - [500_000, 1.0e-4]
    - [1_500_000, 5.0e-5]
    - [2_500_000, 3.0e-5]

# Resources
num_workers: 18
envs_per_worker: 8
num_gpus: 1
