
generators:
  circuit:
    type: 'random'
    args:
      num_gates: 64
  noise:
    type: 'kde_calibration'
    args:
      path: 'data/calibration/belem.json'

num_circuits: 100
use_tqdm: true
seed: 0
