
circuit_generator:
  type: 'random'
  args:
    num_gates: 64
noise_generator:
  type: 'kde_calibration'
  args:
    path: 'data/calibration/mumbai.json'

seed: 0

# Model
hidden_layers: [384, 384]
embedding_dim: 3
entropy_coeff: 5.0e-3
minibatch_size: 2048
batch_size: 32768
sgd_iters: 10
lr_schedule:
    - [0, 1.0e-4]
    - [5_000_000, 5.0e-5]
    - [10_000_000, 2.0e-5]
    - [25_000_000, 1.0e-5]

# Resources
num_workers: 18
envs_per_worker: 8
num_gpus: 1
