
generators:
  circuit:
    type: 'random'
    args:
      num_gates: 128
  noise:
    type: 'kde_calibration'
    args:
      path: 'data/calibration/mumbai.json'

seed: 0

# Model
hidden_layers: [512, 512]
embedding_dim: 3
minibatch_size: 2048
batch_size: 32768
sgd_iters: 10
lr: 5.0e-5

# Resources
num_workers: 18
envs_per_worker: 8
num_gpus: 1
