
generators:
  circuit:
    type: 'random'
    args:
      num_gates: 64
  noise:
    type: 'kde_calibration'
    args:
      path: 'data/calibration/mumbai.json'

seed: 0

# Model
hidden_layers: [512, 512]
embedding_dim: 3
gae_lambda: 0.99
minibatch_size: 2048
batch_size: 32768
sgd_iters: 10
lr_schedule:
    - [0, 1.0e-4]
    - [2_000_000, 5.0e-5]
    - [5_000_000, 1.0e-5]

# Resources
num_workers: 18
envs_per_worker: 8
num_gpus: 1
