
circuit_generator:
  type: 'random'
  args:
    num_gates: 64
noise_generator:
  type: 'kde_calibration'
  args:
    path: 'data/calibration/mumbai.json'

seed: 0

# Model
hidden_layers: [512, 512]
embedding_dim: 5
entropy_coeff: 1.0e-2
minibatch_size: 4096
batch_size: 65536
sgd_iters: 10
lr_schedule:
  - [0, 1.0e-4]
  - [10_000_000, 5.0e-5]
  - [20_000_000, 2.0e-5]
  - [40_000_000, 1.0e-5]

# Resources
num_workers: 18
envs_per_worker: 8
num_gpus: 1
