
circuit_generator:
  type: 'random'
  args:
    num_qubits: 5
    num_gates: 64

noise_generator:
  type: 'uniform'
  args:
    mean: 1.0e-2
    std: 3.0e-3

hidden_layers: [64, 64, 96]
minibatch_size: 256
batch_size: 8192
num_workers: 4
