
generators:
  circuit:
    type: 'random'
    args:
      num_qubits: 16
      num_gates: 128
  noise:
    type: 'uniform'
    args:
      mean: 1.0e-2
      std: 3.0e-3

# Model
hidden_layers: [256, 256, 256]
minibatch_size: 512
batch_size: 16834

# Resources
num_workers: 18
envs_per_worker: 8
num_gpus: 1
