
name: 'belem_no_enhancements'

coupling_map: 't'

obs_modules:
  - type: 'circuit_matrix'
    args:
      depth: 8

allow_bridge_gate: false
commutation_analysis: false
restrict_swaps_to_front_layer: false